# Generated by Django 5.2.7 on 2025-10-21 04:11

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.CharField(max_length=9, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Barangay Name')),
                ('parent_id', models.CharField(max_length=8, verbose_name='Parent ID')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Boundary')),
            ],
        ),
        migrations.CreateModel(
            name='FloodSusceptibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lgu', models.CharField(default='Silay City', max_length=20, verbose_name='LGU')),
                ('psgc_lgu', models.CharField(default='64526000', max_length=8, verbose_name='PSGC_LGU')),
                ('haz_class', models.CharField(default='Flooding', max_length=20, verbose_name='Hazard Class')),
                ('haz_code', models.CharField(choices=[('VHF', 'Very High Flood Susceptibility'), ('HF', 'High Flood Susceptibility'), ('MF', 'Moderate Flood Susceptibility'), ('LF', 'Low Flood Susceptibility')], max_length=3, verbose_name='Hazard Code')),
                ('haz_desc', models.CharField(editable=False, max_length=30, verbose_name='Hazard Description')),
                ('haz_area_ha', models.DecimalField(decimal_places=8, max_digits=15, verbose_name='Hazard Area (Ha)')),
                ('geometry', django.contrib.gis.db.models.fields.MultiPolygonField(srid=4326, verbose_name='Boundary')),
            ],
        ),
    ]
