# Generated by Django 5.2.7 on 2025-11-17 01:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssessmentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=100, verbose_name='Barangay')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitude')),
                ('flood_risk_code', models.CharField(max_length=3, verbose_name='Flood Risk Code')),
                ('flood_risk_description', models.CharField(max_length=100, verbose_name='Flood Risk Description')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Assessment Date/Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Staff Member')),
            ],
            options={
                'verbose_name': 'Assessment Record',
                'verbose_name_plural': 'Assessment Records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='CertificateRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('establishment_name', models.CharField(max_length=200, verbose_name='Establishment Name')),
                ('owner_name', models.CharField(max_length=200, verbose_name='Owner Name')),
                ('location', models.TextField(verbose_name='Location')),
                ('barangay', models.CharField(max_length=100, verbose_name='Barangay')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitude')),
                ('flood_susceptibility', models.CharField(max_length=100, verbose_name='Flood Susceptibility')),
                ('zone_status', models.CharField(max_length=100, verbose_name='Zone Status')),
                ('issue_date', models.CharField(max_length=100, verbose_name='Issue Date')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Certificate Generated Date/Time')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.assessmentrecord', verbose_name='Related Assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Staff Member')),
            ],
            options={
                'verbose_name': 'Certificate Record',
                'verbose_name_plural': 'Certificate Records',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='FloodRecordActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('CREATE', 'Created'), ('UPDATE', 'Updated'), ('DELETE', 'Deleted')], max_length=10, verbose_name='Action')),
                ('flood_record_id', models.IntegerField(blank=True, null=True, verbose_name='Flood Record ID')),
                ('event_type', models.CharField(max_length=200, verbose_name='Event Type')),
                ('event_date', models.DateTimeField(verbose_name='Event Date')),
                ('affected_barangays', models.CharField(max_length=500, verbose_name='Affected Barangays')),
                ('casualties_dead', models.IntegerField(default=0, verbose_name='Deaths')),
                ('casualties_injured', models.IntegerField(default=0, verbose_name='Injured')),
                ('casualties_missing', models.IntegerField(default=0, verbose_name='Missing')),
                ('affected_persons', models.IntegerField(default=0, verbose_name='Affected Persons')),
                ('affected_families', models.IntegerField(default=0, verbose_name='Affected Families')),
                ('damage_total_php', models.FloatField(default=0, verbose_name='Total Damage (PHP)')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Activity Date/Time')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Staff Member')),
            ],
            options={
                'verbose_name': 'Flood Record Activity',
                'verbose_name_plural': 'Flood Record Activities',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ReportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay', models.CharField(max_length=100, verbose_name='Barangay')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10, verbose_name='Longitude')),
                ('flood_risk_code', models.CharField(max_length=3, verbose_name='Flood Risk Code')),
                ('flood_risk_label', models.CharField(max_length=100, verbose_name='Flood Risk Label')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Report Generated Date/Time')),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='maps.assessmentrecord', verbose_name='Related Assessment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Staff Member')),
            ],
            options={
                'verbose_name': 'Report Record',
                'verbose_name_plural': 'Report Records',
                'ordering': ['-timestamp'],
            },
        ),
    ]
