# Generated by Django 5.2.7 on 2025-11-20 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_assessmentrecord_certificaterecord_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentrecord',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archived Date/Time'),
        ),
        migrations.AddField(
            model_name='assessmentrecord',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='certificaterecord',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archived Date/Time'),
        ),
        migrations.AddField(
            model_name='certificaterecord',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='floodrecordactivity',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archived Date/Time'),
        ),
        migrations.AddField(
            model_name='floodrecordactivity',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='reportrecord',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archived Date/Time'),
        ),
        migrations.AddField(
            model_name='reportrecord',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archived'),
        ),
        migrations.AddIndex(
            model_name='assessmentrecord',
            index=models.Index(fields=['-timestamp'], name='maps_assess_timesta_e93006_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentrecord',
            index=models.Index(fields=['is_archived', '-timestamp'], name='maps_assess_is_arch_a366ef_idx'),
        ),
        migrations.AddIndex(
            model_name='certificaterecord',
            index=models.Index(fields=['-timestamp'], name='maps_certif_timesta_9d9fe4_idx'),
        ),
        migrations.AddIndex(
            model_name='certificaterecord',
            index=models.Index(fields=['is_archived', '-timestamp'], name='maps_certif_is_arch_8ff8cb_idx'),
        ),
        migrations.AddIndex(
            model_name='floodrecordactivity',
            index=models.Index(fields=['-timestamp'], name='maps_floodr_timesta_c4cace_idx'),
        ),
        migrations.AddIndex(
            model_name='floodrecordactivity',
            index=models.Index(fields=['is_archived', '-timestamp'], name='maps_floodr_is_arch_76a477_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrecord',
            index=models.Index(fields=['-timestamp'], name='maps_report_timesta_3a43e1_idx'),
        ),
        migrations.AddIndex(
            model_name='reportrecord',
            index=models.Index(fields=['is_archived', '-timestamp'], name='maps_report_is_arch_b702a4_idx'),
        ),
    ]
