# Generated by Django 5.2.5 on 2025-11-20 17:05

import django.core.validators
import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_custom_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=models.ImageField(blank=True, help_text='Upload a profile image (JPG, PNG, or GIF, max 5MB, max 4000x4000px)', null=True, upload_to='profile_images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'gif']), users.models.validate_image_size, users.models.validate_image_dimensions], verbose_name='Profile Image'),
        ),
    ]
