# Generated by Django 5.2.7 on 2025-11-20 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='userlog',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Archived Date/Time'),
        ),
        migrations.AddField(
            model_name='userlog',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Archived'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['-timestamp'], name='users_userl_timesta_f5d8a2_idx'),
        ),
        migrations.AddIndex(
            model_name='userlog',
            index=models.Index(fields=['is_archived', '-timestamp'], name='users_userl_is_arch_33cf8a_idx'),
        ),
    ]
