# Generated by Django 5.2.7 on 2025-11-17 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('affected_barangays', models.CharField(max_length=500)),
                ('casualties_dead', models.IntegerField(default=0)),
                ('casualties_injured', models.IntegerField(default=0)),
                ('casualties_missing', models.IntegerField(default=0)),
                ('affected_persons', models.IntegerField(default=0)),
                ('affected_families', models.IntegerField(default=0)),
                ('houses_damaged_partially', models.IntegerField(default=0)),
                ('houses_damaged_totally', models.IntegerField(default=0)),
                ('damage_infrastructure_php', models.FloatField(default=0)),
                ('damage_agriculture_php', models.FloatField(default=0)),
                ('damage_institutions_php', models.FloatField(default=0)),
                ('damage_private_commercial_php', models.FloatField(default=0)),
                ('damage_total_php', models.FloatField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='rainfalldata',
            name='location',
        ),
        migrations.RemoveField(
            model_name='tideleveldata',
            name='location',
        ),
        migrations.RemoveField(
            model_name='weatherdata',
            name='location',
        ),
        migrations.AddField(
            model_name='rainfalldata',
            name='station_name',
            field=models.CharField(default='Silay City', max_length=100),
        ),
        migrations.AddField(
            model_name='tideleveldata',
            name='station_name',
            field=models.CharField(default='Silay City', max_length=100),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='station_name',
            field=models.CharField(default='Silay City', max_length=100),
        ),
        migrations.AddField(
            model_name='weatherdata',
            name='wind_speed_kph',
            field=models.FloatField(default=10),
        ),
        migrations.AlterField(
            model_name='rainfalldata',
            name='value_mm',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tideleveldata',
            name='height_m',
            field=models.FloatField(default=0.8),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='humidity_percent',
            field=models.IntegerField(default=75),
        ),
        migrations.AlterField(
            model_name='weatherdata',
            name='temperature_c',
            field=models.FloatField(default=28.5),
        ),
    ]
