# Generated by Django 5.2.5 on 2025-11-19 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitoring', '0003_benchmarksettings'),
        ('monitoring', '0005_combined_risk_method'),
    ]

    operations = [
    ]
